const it = {
  skip: 'Vai al contenuto',
  nav: 'Navigazione principale',
  openMenu: 'Apri menu',
  closeMenu: 'Chiudi menu',
  language: 'Lingua',
  missingTranslation: 'Traduzione non disponibile in questa anteprima',
  closeRequest: 'Chiudi la richiesta',
  closeChat: 'Chiudi chat',
  openChat: 'Apri chat WhatsApp',
  breadcrumb: 'Percorso',
  related: 'Altre prestazioni',
  contact: 'Contatti',
  hours: 'Orari della clinica',
  tollFree: 'Numero verde',
  socialUnavailable: 'Link non configurato nella fonte',
  carousel: 'carosello',
  slide: 'diapositiva',
  of: 'di',
  previous: 'Testimonianza precedente',
  next: 'Testimonianza successiva',
  showSlide: 'Mostra testimonianza',
  watchVideo: 'Guarda il video',
  rating: 'Valutazione Google 4,9 su 5 basata su 152 recensioni',
  stars: 'Valutazione di cinque stelle',
  logo: 'DentVitalis - Dentisti Croazia',
};
const hr: typeof it = {
  skip: 'Preskoči na sadržaj',
  nav: 'Glavna navigacija',
  openMenu: 'Otvori izbornik',
  closeMenu: 'Zatvori izbornik',
  language: 'Jezik',
  missingTranslation: 'Prijevod nije dostupan u ovom pretpregledu',
  closeRequest: 'Zatvori upit',
  closeChat: 'Zatvori razgovor',
  openChat: 'Otvori WhatsApp razgovor',
  breadcrumb: 'Putanja stranice',
  related: 'Ostale usluge',
  contact: 'Kontakti',
  hours: 'Radno vrijeme',
  tollFree: 'Besplatni broj',
  socialUnavailable: 'Poveznica nije navedena u izvoru',
  carousel: 'klizač',
  slide: 'slajd',
  of: 'od',
  previous: 'Prethodno iskustvo pacijenta',
  next: 'Sljedeće iskustvo pacijenta',
  showSlide: 'Prikaži iskustvo pacijenta',
  watchVideo: 'Pogledaj video',
  rating: 'Google ocjena 4,9 od 5 na temelju 152 recenzije',
  stars: 'Ocjena pet zvjezdica',
  logo: 'DentVitalis',
};
export const ui = (lang: string) => (lang === 'hr' ? hr : it);
