const it = {
  skip: 'Vai al contenuto',
  nav: 'Navigazione principale',
  openMenu: 'Apri menu',
  closeMenu: 'Chiudi menu',
  language: 'Lingua',
  missingTranslation: 'Traduzione non disponibile in questa anteprima',
  closeRequest: 'Chiudi la richiesta',
  closeChat: 'Chiudi chat',
  openChat: 'Apri chat WhatsApp',
  breadcrumb: 'Percorso',
  related: 'Altre prestazioni',
  contact: 'Contatti',
  hours: 'Orari della clinica',
  tollFree: 'Numero verde',
  socialUnavailable: 'Link non configurato nella fonte',
  carousel: 'carosello',
  slide: 'diapositiva',
  of: 'di',
  previous: 'Testimonianza precedente',
  next: 'Testimonianza successiva',
  showSlide: 'Mostra testimonianza',
  watchVideo: 'Guarda il video',
  rating: 'Valutazione Google 4,9 su 5 basata su 152 recensioni',
  stars: 'Valutazione di cinque stelle',
  logo: 'DentVitalis - Dentisti Croazia',
};
const hr: typeof it = {
  skip: 'Preskoči na sadržaj',
  nav: 'Glavna navigacija',
  openMenu: 'Otvori izbornik',
  closeMenu: 'Zatvori izbornik',
  language: 'Jezik',
  missingTranslation: 'Prijevod nije dostupan u ovom pretpregledu',
  closeRequest: 'Zatvori upit',
  closeChat: 'Zatvori razgovor',
  openChat: 'Otvori WhatsApp razgovor',
  breadcrumb: 'Putanja stranice',
  related: 'Ostale usluge',
  contact: 'Kontakti',
  hours: 'Radno vrijeme',
  tollFree: 'Besplatni broj',
  socialUnavailable: 'Poveznica nije navedena u izvoru',
  carousel: 'klizač',
  slide: 'slajd',
  of: 'od',
  previous: 'Prethodno iskustvo pacijenta',
  next: 'Sljedeće iskustvo pacijenta',
  showSlide: 'Prikaži iskustvo pacijenta',
  watchVideo: 'Pogledaj video',
  rating: 'Google ocjena 4,9 od 5 na temelju 152 recenzije',
  stars: 'Ocjena pet zvjezdica',
  logo: 'DentVitalis',
};
const de: typeof it = {
  skip: 'Zum Inhalt springen',
  nav: 'Hauptnavigation',
  openMenu: 'Menü öffnen',
  closeMenu: 'Menü schließen',
  language: 'Sprache',
  missingTranslation: 'Übersetzung in dieser Vorschau noch nicht verfügbar',
  closeRequest: 'Anfrage schließen',
  closeChat: 'Chat schließen',
  openChat: 'WhatsApp-Chat öffnen',
  breadcrumb: 'Seitenpfad',
  related: 'Weitere Leistungen',
  contact: 'Kontakt',
  hours: 'Öffnungszeiten',
  tollFree: 'Kostenlose Rufnummer',
  socialUnavailable: 'Kein Link in der Quelle angegeben',
  carousel: 'Karussell',
  slide: 'Folie',
  of: 'von',
  previous: 'Vorheriger Erfahrungsbericht',
  next: 'Nächster Erfahrungsbericht',
  showSlide: 'Erfahrungsbericht anzeigen',
  watchVideo: 'Video ansehen',
  rating: 'Google-Bewertung 4,9 von 5, basierend auf 152 Bewertungen',
  stars: 'Fünf-Sterne-Bewertung',
  logo: 'DentVitalis – Zahnärzte Kroatien',
};
export const homeHref = (lang: string) =>
  lang === 'it' ? '/' : `/${lang === 'sl' ? 'si' : lang}/`;
export const ui = (lang: string) =>
  lang === 'hr'
    ? hr
    : lang === 'de'
      ? de
      : lang === 'en'
        ? en
        : lang === 'sl'
          ? sl
          : it;
const en: typeof it = {
  skip: 'Skip to content',
  nav: 'Main navigation',
  openMenu: 'Open menu',
  closeMenu: 'Close menu',
  language: 'Language',
  missingTranslation: 'Translation is not available in this preview',
  closeRequest: 'Close enquiry',
  closeChat: 'Close chat',
  openChat: 'Open WhatsApp chat',
  breadcrumb: 'Breadcrumb',
  related: 'Other services',
  contact: 'Contact',
  hours: 'Opening hours',
  tollFree: 'Freephone',
  socialUnavailable: 'Link not provided in the source',
  carousel: 'carousel',
  slide: 'slide',
  of: 'of',
  previous: 'Previous testimonial',
  next: 'Next testimonial',
  showSlide: 'Show testimonial',
  watchVideo: 'Watch video',
  rating: 'Google rating 4.9 out of 5 based on 152 reviews',
  stars: 'Five-star rating',
  logo: 'DentVitalis',
};

const sl: typeof it = {
  skip: 'Preskoči na vsebino',
  nav: 'Glavna navigacija',
  openMenu: 'Odpri meni',
  closeMenu: 'Zapri meni',
  language: 'Jezik',
  missingTranslation: 'Prevod v tem predogledu ni na voljo',
  closeRequest: 'Zapri povpraševanje',
  closeChat: 'Zapri pogovor',
  openChat: 'Odpri pogovor WhatsApp',
  breadcrumb: 'Pot strani',
  related: 'Druge storitve',
  contact: 'Stiki',
  hours: 'Delovni čas',
  tollFree: 'Brezplačna številka',
  socialUnavailable: 'Povezava ni navedena v viru',
  carousel: 'vrtiljak',
  slide: 'diapozitiv',
  of: 'od',
  previous: 'Prejšnja izkušnja pacienta',
  next: 'Naslednja izkušnja pacienta',
  showSlide: 'Prikaži izkušnjo pacienta',
  watchVideo: 'Oglejte si video',
  rating: 'Ocena Google 4,9 od 5 na podlagi 152 ocen',
  stars: 'Ocena pet zvezdic',
  logo: 'DentVitalis',
};
