"""Package exact fonts in a shared binary FontFace loader and native CSS fallback.

Optional regeneration only: pip install fonttools==4.59.1 brotli==1.1.0
Normal Astro builds consume committed assets/manifest, with no Python dependency.
"""
import base64
import hashlib
import io
import json
from pathlib import Path

from fontTools.ttLib import TTFont, woff2

ROOT = Path(__file__).resolve().parents[1]
LATIN = ROOT / "reference/webflow-handoff/2026-09-07/extracted/assets/fonts"
EXTENDED = ROOT / "source-assets/fonts/montserrat-v31"
FACES = [
    (300, "normal", "JTUHjIg1_i6t8kCHKm4532VJOt5-QNFgpCs16Hw5aX8.ttf"),
    (400, "normal", "JTUHjIg1_i6t8kCHKm4532VJOt5-QNFgpCtr6Hw5aX8.ttf"),
    (500, "normal", "JTUHjIg1_i6t8kCHKm4532VJOt5-QNFgpCtZ6Hw5aX8.ttf"),
    (600, "normal", "JTUHjIg1_i6t8kCHKm4532VJOt5-QNFgpCu173w5aX8.ttf"),
    (700, "normal", "JTUHjIg1_i6t8kCHKm4532VJOt5-QNFgpCuM73w5aX8.ttf"),
    (800, "normal", "JTUHjIg1_i6t8kCHKm4532VJOt5-QNFgpCvr73w5aX8.ttf"),
    (400, "italic", "JTUFjIg1_i6t8kCHKm459Wx7xQYXK0vOoz6jq6R9WXh0ow.ttf"),
    ("300 800", "normal", "JTUSjIg1_i6t8kCHKm459Wdhyzbi.woff2"),
    (400, "italic", "JTUQjIg1_i6t8kCHKm459WxRxy7mw9c.woff2"),
]
# Preserve the original extended face selection, including overlapping symbols.
EXTENDED_RANGE = (
    "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,"
    "U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,"
    "U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
)
extended_points = set()
for part in EXTENDED_RANGE.split(","):
    bounds = [int(value, 16) for value in part[2:].split("-")]
    extended_points.update(range(bounds[0], bounds[-1] + 1))


def sha(data):
    return hashlib.sha256(data).hexdigest()


rules, faces, binaries = [], [], []
for weight, style, name in FACES:
    source = (LATIN if name.endswith(".ttf") else EXTENDED) / name
    original = source.read_bytes()
    font = TTFont(io.BytesIO(original))
    if name.endswith(".ttf"):
        output = io.BytesIO()
        woff2.compress(io.BytesIO(original), output)
        packed = output.getvalue()
        restored = TTFont(io.BytesIO(packed))
        assert font.getBestCmap() == restored.getBestCmap()
        assert font["hmtx"].metrics == restored["hmtx"].metrics
        # Match the original extended face coverage. No glyphs are removed.
        coverage = ",".join(
            f"U+{point:04X}"
            for point in sorted(set(font.getBestCmap()) - extended_points)
        )
    else:
        packed = original
        coverage = EXTENDED_RANGE
    family = "Montserrat" if name.endswith(".ttf") else "Montserrat Extended"
    binaries.append([family, str(weight), style, coverage, base64.b64encode(packed).decode()])
    rules.append(
        f"@font-face{{font-family:'{family}';"
        f"font-weight:{weight};font-style:{style};font-display:block;"
        f"src:url(data:font/woff2;base64,{base64.b64encode(packed).decode()}) format('woff2');"
        f"unicode-range:{coverage};}}"
    )
    faces.append({
        "source": str(source.relative_to(ROOT)), "sourceSha256": sha(original),
        "sourceBytes": len(original), "woff2Sha256": sha(packed),
        "woff2Bytes": len(packed), "weight": weight, "style": style, "family": family,
        "unicodeRange": coverage,
    })

css = ("/* Generated by scripts/prepare-font-styles.py; do not edit. */\n" + "\n".join(rules)).encode()
path = f"/assets/fonts/montserrat-{sha(css)[:12]}.css"
target = ROOT / "public" / path.lstrip("/")
if target.exists():
    assert target.read_bytes() == css
else:
    target.write_bytes(css)
script = ("/* Generated by scripts/prepare-font-styles.py; do not edit. */\n"
          "if (typeof FontFace !== 'undefined' && document.fonts) {\n"
          "for (const [family, weight, style, unicodeRange, data] of "
          + json.dumps(binaries, separators=(",", ":")) + ") {\n"
          "const bytes = Uint8Array.from(atob(data), c => c.charCodeAt(0));\n"
          "const face = new FontFace(family, bytes, {weight, style, unicodeRange, display:'block'});\n"
          "if (face.status === 'loaded') document.fonts.add(face);\n"
          "}\n}\n").encode()
script_path = f"/assets/fonts/montserrat-{sha(script)[:12]}.js"
script_target = ROOT / "public" / script_path.lstrip("/")
if script_target.exists():
    assert script_target.read_bytes() == script
else:
    script_target.write_bytes(script)
manifest = {
    "stylesheet": path, "sha256": sha(css), "bytes": len(css),
    "script": script_path, "scriptSha256": sha(script), "scriptBytes": len(script),
    "generator": "fonttools 4.59.1 / brotli 1.1.0", "faces": faces,
}
(ROOT / "src/content/font-styles.json").write_text(json.dumps(manifest, indent=2) + "\n")
print(f"{path}: {len(css):,} CSS bytes; {sum(f['woff2Bytes'] for f in faces):,} font bytes")
